import { FileText } from "lucide-react";

export const TermsOfService = () => {
  return (
    <div className="max-w-4xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
      <div className="bg-slate-800 border border-slate-700/50 rounded-sm p-8 md:p-12 shadow-[0_0_40px_rgba(0,0,0,0.5)]">
        <div className="flex items-center gap-3 mb-8 border-b border-slate-700 pb-6">
          <div className="bg-emerald-primary p-2 rounded-sm shadow-[2px_2px_0_0_rgba(255,255,255,0.2)]">
            <FileText className="h-8 w-8 text-white" strokeWidth={3} />
          </div>
          <h1 className="text-4xl font-black text-white tracking-tight uppercase">User Agreement Code</h1>
        </div>

        <div className="prose prose-invert prose-slate max-w-none prose-headings:text-emerald-primary text-gray-400">
          <p className="mb-6 font-bold text-white tracking-widest text-xs uppercase">Version 1.0.4 | Initiated 2026</p>
          
          <p className="mb-6">
            By activating an endpoint on Flexio, you are technically bound to the parameters listed below. We designed our system for
            pure functionality, so these terms strip the usual legal bloating down to the critical core operating instructions.
          </p>

          <h2 className="text-xl font-bold tracking-widest uppercase mt-8 mb-4 border-b border-slate-700 pb-2">Operational Bounds</h2>
          <p className="mb-4">
            You agree to use this platform exclusively for personal athletic optimization. You may not deploy bots, scripts, or scrape the neural output
            generated by your terminal for wholesale commercial redistribution.
          </p>

          <h2 className="text-xl font-bold tracking-widest uppercase mt-8 mb-4 border-b border-slate-700 pb-2">Medical Disclaimer Override</h2>
          <p className="mb-6 border-l-4 border-yellow-500 pl-4 bg-yellow-500/10 py-2">
            <strong>WARNING: </strong>
            Flexio is an advanced algorithmic planning system, NOT a certified physician. 
            The AI outputs generated for BMI, Workouts, and Sleep are statistical matrices. 
            You must consult a biological medical professional before drastically altering your mechanical output or diet logic.
          </p>

          <h2 className="text-xl font-bold tracking-widest uppercase mt-8 mb-4 border-b border-slate-700 pb-2">Account Stability</h2>
          <p className="mb-6">
            You are exclusively responsible for the integrity of your authentication tokens. If your login credentials are compromised through external phishing or endpoint corruption on your native hardware, Flexio assumes no liability for unauthorized data injections into your sleep or workout logs.
          </p>

          <h2 className="text-xl font-bold tracking-widest uppercase mt-8 mb-4 border-b border-slate-700 pb-2">Termination Protocol</h2>
          <p className="mb-6">
            We reserve the right to forcefully un-sync any account detected executing malicious requests against our backend REST infrastructure or intentionally attempting to crash the predictive algorithms.
          </p>
        </div>
      </div>
    </div>
  );
};
